// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's profile (name, role, school).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb2 = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const userId = ctx.getUserId();
    const [{ data: profile }, { data: roles }] = await Promise.all([
      sb2.from("profiles").select("*").eq("id", userId).maybeSingle(),
      sb2.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const payload = {
      user_id: userId,
      email: ctx.getUserEmail(),
      profile,
      roles: (roles || []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-news.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_news_default = defineTool2({
  name: "list_news",
  title: "List school news",
  description: "List recent published news items from the school.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max items to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await sb(ctx).from("news").select("id, title, content, created_at, published").eq("published", true).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data }
    };
  }
});

// src/lib/mcp/tools/list-inbox.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_inbox_default = defineTool3({
  name: "list_my_notifications",
  title: "List my notifications",
  description: "List the signed-in user's most recent notifications from their inbox.",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).default(20),
    unread_only: z2.boolean().default(false).describe("Only return unread notifications")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb2 = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = sb2.from("notifications").select("id, title, body, created_at, read_at, type").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (unread_only) q = q.is("read_at", null);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dlkyxvhnnffblerwedjz";
var mcp_default = defineMcp({
  name: "school-mcp",
  title: "School Management MCP",
  version: "0.1.0",
  instructions: "Tools for the school management system. Use `whoami` to identify the signed-in user, `list_news` to fetch recent school news, and `list_my_notifications` to check the user's inbox.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_news_default, list_inbox_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
