DO $extguard$
BEGIN
  EXECUTE 'CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA pg_catalog';
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'skip extension: %', SQLERRM;
END
$extguard$;
DO $extguard$
BEGIN
  EXECUTE 'CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions';
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'skip extension: %', SQLERRM;
END
$extguard$;
