DROP POLICY IF EXISTS "task attach read" ON storage.objects;
DROP POLICY IF EXISTS "task attach read" ON storage.objects;
create policy "task attach read" on storage.objects for select to authenticated using (bucket_id = 'task-attachments');
DROP POLICY IF EXISTS "task attach insert own" ON storage.objects;
DROP POLICY IF EXISTS "task attach insert own" ON storage.objects;
create policy "task attach insert own" on storage.objects for insert to authenticated with check (bucket_id = 'task-attachments' and (storage.foldername(name))[1] = auth.uid()::text);
DROP POLICY IF EXISTS "task attach update own" ON storage.objects;
DROP POLICY IF EXISTS "task attach update own" ON storage.objects;
create policy "task attach update own" on storage.objects for update to authenticated using (bucket_id = 'task-attachments' and (storage.foldername(name))[1] = auth.uid()::text);
DROP POLICY IF EXISTS "task attach delete own" ON storage.objects;
DROP POLICY IF EXISTS "task attach delete own" ON storage.objects;
create policy "task attach delete own" on storage.objects for delete to authenticated using (bucket_id = 'task-attachments' and (storage.foldername(name))[1] = auth.uid()::text);