
ALTER TABLE public.id_plan_records
  ADD COLUMN IF NOT EXISTS order_ref_type TEXT,
  ADD COLUMN IF NOT EXISTS order_ref_number TEXT,
  ADD COLUMN IF NOT EXISTS order_ref_date DATE,
  ADD COLUMN IF NOT EXISTS start_datetime TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS end_datetime TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS location TEXT,
  ADD COLUMN IF NOT EXISTS duration_days INTEGER,
  ADD COLUMN IF NOT EXISTS objectives TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS knowledge_summary TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS applications TEXT[] NOT NULL DEFAULT '{}';
