
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS national_id text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS date_of_birth date;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS gender text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS nationality text DEFAULT 'ไทย';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS ethnicity text DEFAULT 'ไทย';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS religion text DEFAULT 'พุทธ';
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS blood_type text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS photo_url text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS birth_province text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS previous_school text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS admission_date date;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS special_needs text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS father_name text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS father_id text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS father_phone text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS father_occupation text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS mother_name text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS mother_id text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS mother_phone text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS mother_occupation text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS guardian_name text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS guardian_phone text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS guardian_relation text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emergency_contact text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS emergency_phone text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS weight numeric;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS height numeric;
